### ISSUE TITLE
Error when parsing using Serialize

### ISSUE THREAD

**Issue by lzrdblzzrd** [dotX12/ShazamIO#18]
Code:
```
from shazamio import Shazam, Serialize

shazam = Shazam()


async def recognize(file_path):
    song_info = await shazam.recognize_song(file_path)
    return Serialize.full_track(song_info)
```

Exception:
```
Invalid data at path [1, _sections, track]: No suitable parsers in union found for `{'type': 'LYRICS', 'text': ['Haha!', "It's Reid", 'Welcome to my hotel room', 'A hotel room freestyle', "You already know, let's go", 'It goes like this, it goes exactly like this', '', 'Life goes on like a windmill', 'Only plot I got is to grip steal, make a mill', "Stayin' real, always ill from 1993 til", 'Souls of mischief did it better still', 'Whatever on ya skin like leather', 'Flap ya like a feather', "Don't depend on the weather", "You know I'm better", 'Than most these clowns', "Ya be seein' on the TV", "Cause I don't need cream, I got enough for me see", "I'm like a dairy farm I make cheese when I please", 'This untapped potential have you stuck on ya knees', 'Spewing goop like a slut when they sneeze', 'Jack ya wallet with ease', 'Bruised lids from a lack of sleep', 'Put a chrome to ya dome and eject the meat', "I'll take my seat now", 'Big G on the beats, kaplow', "Don't move dude", 'I got some more food for ya mouth', "Turn this old church to a fuckin' slaughterhouse", '', 'But hold the phone', 'Pick up all the pieces of ya head blown', "I love drugs but I'll never condone", 'Knockout a cop in the comfort of my own home', "Fuck pigs til I'm six feet overgrown", 'Head to hell screamin\' "Fuck 12"', "'Til I'm out the ozone", "Then dust 'em off like a camera lens", 'Whip a Benz', "Y'all should really see how far my shawty bends", 'And how my shotty ends life', 'Put 2 through you and save the rest for ya wife, bitch good night', 'I love my wife, but fuck life', 'Could get a murder charge just to see what the fuck it feels like', 'Leave me alone', 'Could give a fuck who you with bitch', 'I said leave me alone', 'Feed ya Momma a bone', 'Give her a treat if she make me a scone', 'Live ya life and get the fuck off ya phone', "Appreciate the moment and you'll never be alone", '', "I can't surf, but I'm gnar like Spicolli", 'Flat ya like some dough', 'And cut ya up like pepperoni', 'Personal pan pizza in the oven', "Bitch I'm hungry", 'I eat these fools faster than a motherfucking humvee', 'My honey got a rump that make', 'Humpty Dumpty land on his feet', 'Capiche?', 'Damn Reid be off the leash', '', 'I been kicked around, eaten up chewed and spit out', 'My mind was torn into pieces so I ripped that shit out', "Ten years down the drain, guess I wasn't cut out", 'Fast forward 2020, who you listen to now? (Reid)', "Mothafucka's gettin' sick off the clout", "They'd rather suck each other off", 'Instead of figure it out', "Reid's here to patch it up like a squeaky leaky water spout (Bitch)", '', 'Like a squeaky leaky water spout (Uh, Bitch)', 'Imma clean this shit up', 'Imma kill this shit', 'Just for fun', "I don't even have to", "Someone's gotta do it", "That's why I'm here", 'Hot Vodka Volume 1'], 'footer': 'Writer(s): Tanner Petulla\nLyrics powered by www.musixmatch.com', 'tabname': 'Lyrics', 'beacondata': {'lyricsid': '27638669', 'providername': 'musixmatch', 'commontrackid': '110409337'}}`
Suberrors:
  * get_complex_parser.<locals>.complex_parser: __init__() missing 2 required positional arguments: 'meta_pages' and 'metadata'
  * get_complex_parser.<locals>.complex_parser: __init__() missing 1 required positional argument: 'youtube_url'
  * get_complex_parser.<locals>.complex_parser: __init__() missing 1 required positional argument: 'url'
Traceback (most recent call last):
  File "/home/lzrdblzzrd/.cache/pypoetry/virtualenvs/lzrdbot-QMN38oMy-py3.8/lib/python3.8/site-packages/dataclass_factory/parsers.py", line 46, in dyn_element_parser
    return parser(data)
  File "/home/lzrdblzzrd/.cache/pypoetry/virtualenvs/lzrdbot-QMN38oMy-py3.8/lib/python3.8/site-packages/dataclass_factory/parsers.py", line 99, in union_parser
    raise UnionParseError("No suitable parsers in union found for `%s`" % data, errors)
dataclass_factory.exceptions.UnionParseError: No suitable parsers in union found for `{'type': 'LYRICS', 'text': ['Haha!', "It's Reid", 'Welcome to my hotel room', 'A hotel room freestyle', "You already know, let's go", 'It goes like this, it goes exactly like this', '', 'Life goes on like a windmill', 'Only plot I got is to grip steal, make a mill', "Stayin' real, always ill from 1993 til", 'Souls of mischief did it better still', 'Whatever on ya skin like leather', 'Flap ya like a feather', "Don't depend on the weather", "You know I'm better", 'Than most these clowns', "Ya be seein' on the TV", "Cause I don't need cream, I got enough for me see", "I'm like a dairy farm I make cheese when I please", 'This untapped potential have you stuck on ya knees', 'Spewing goop like a slut when they sneeze', 'Jack ya wallet with ease', 'Bruised lids from a lack of sleep', 'Put a chrome to ya dome and eject the meat', "I'll take my seat now", 'Big G on the beats, kaplow', "Don't move dude", 'I got some more food for ya mouth', "Turn this old church to a fuckin' slaughterhouse", '', 'But hold the phone', 'Pick up all the pieces of ya head blown', "I love drugs but I'll never condone", 'Knockout a cop in the comfort of my own home', "Fuck pigs til I'm six feet overgrown", 'Head to hell screamin\' "Fuck 12"', "'Til I'm out the ozone", "Then dust 'em off like a camera lens", 'Whip a Benz', "Y'all should really see how far my shawty bends", 'And how my shotty ends life', 'Put 2 through you and save the rest for ya wife, bitch good night', 'I love my wife, but fuck life', 'Could get a murder charge just to see what the fuck it feels like', 'Leave me alone', 'Could give a fuck who you with bitch', 'I said leave me alone', 'Feed ya Momma a bone', 'Give her a treat if she make me a scone', 'Live ya life and get the fuck off ya phone', "Appreciate the moment and you'll never be alone", '', "I can't surf, but I'm gnar like Spicolli", 'Flat ya like some dough', 'And cut ya up like pepperoni', 'Personal pan pizza in the oven', "Bitch I'm hungry", 'I eat these fools faster than a motherfucking humvee', 'My honey got a rump that make', 'Humpty Dumpty land on his feet', 'Capiche?', 'Damn Reid be off the leash', '', 'I been kicked around, eaten up chewed and spit out', 'My mind was torn into pieces so I ripped that shit out', "Ten years down the drain, guess I wasn't cut out", 'Fast forward 2020, who you listen to now? (Reid)', "Mothafucka's gettin' sick off the clout", "They'd rather suck each other off", 'Instead of figure it out', "Reid's here to patch it up like a squeaky leaky water spout (Bitch)", '', 'Like a squeaky leaky water spout (Uh, Bitch)', 'Imma clean this shit up', 'Imma kill this shit', 'Just for fun', "I don't even have to", "Someone's gotta do it", "That's why I'm here", 'Hot Vodka Volume 1'], 'footer': 'Writer(s): Tanner Petulla\nLyrics powered by www.musixmatch.com', 'tabname': 'Lyrics', 'beacondata': {'lyricsid': '27638669', 'providername': 'musixmatch', 'commontrackid': '110409337'}}`
Suberrors:
  * get_complex_parser.<locals>.complex_parser: __init__() missing 2 required positional arguments: 'meta_pages' and 'metadata'
  * get_complex_parser.<locals>.complex_parser: __init__() missing 1 required positional argument: 'youtube_url'
  * get_complex_parser.<locals>.complex_parser: __init__() missing 1 required positional argument: 'url'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lzrdblzzrd/.cache/pypoetry/virtualenvs/lzrdbot-QMN38oMy-py3.8/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/lzrdblzzrd/PycharmProjects/LZRDBot/client_bot.py", line 33, in _
    song_info = await recognize(file_path)
  File "/home/lzrdblzzrd/PycharmProjects/LZRDBot/modules/shazam.py", line 8, in recognize
    return Serialize.full_track(song_info)
  File "/home/lzrdblzzrd/.cache/pypoetry/virtualenvs/lzrdbot-QMN38oMy-py3.8/lib/python3.8/site-packages/shazamio/serializers.py", line 24, in full_track
    return FACTORY_TRACK.load(data, ResponseTrack)
  File "/home/lzrdblzzrd/.cache/pypoetry/virtualenvs/lzrdbot-QMN38oMy-py3.8/lib/python3.8/site-packages/dataclass_factory/factory.py", line 213, in load
    return self.parser(class_)(data)
  File "/home/lzrdblzzrd/.cache/pypoetry/virtualenvs/lzrdbot-QMN38oMy-py3.8/lib/python3.8/site-packages/dataclass_factory/parsers.py", line 223, in complex_parser
    result = parser(data[item_name])
  File "/home/lzrdblzzrd/.cache/pypoetry/virtualenvs/lzrdbot-QMN38oMy-py3.8/lib/python3.8/site-packages/dataclass_factory/parsers.py", line 34, in element_parser
    return parser(data)
  File "/home/lzrdblzzrd/.cache/pypoetry/virtualenvs/lzrdbot-QMN38oMy-py3.8/lib/python3.8/site-packages/dataclass_factory/parsers.py", line 260, in optional_parser
    return parser(data) if data is not None else None
  File "/home/lzrdblzzrd/.cache/pypoetry/virtualenvs/lzrdbot-QMN38oMy-py3.8/lib/python3.8/site-packages/dataclass_factory/parsers.py", line 223, in complex_parser
    result = parser(data[item_name])
  File "/home/lzrdblzzrd/.cache/pypoetry/virtualenvs/lzrdbot-QMN38oMy-py3.8/lib/python3.8/site-packages/dataclass_factory/parsers.py", line 34, in element_parser
    return parser(data)
  File "/home/lzrdblzzrd/.cache/pypoetry/virtualenvs/lzrdbot-QMN38oMy-py3.8/lib/python3.8/site-packages/dataclass_factory/parsers.py", line 260, in optional_parser
    return parser(data) if data is not None else None
  File "/home/lzrdblzzrd/.cache/pypoetry/virtualenvs/lzrdbot-QMN38oMy-py3.8/lib/python3.8/site-packages/dataclass_factory/parsers.py", line 79, in collection_parser
    return collection_factory(
  File "/home/lzrdblzzrd/.cache/pypoetry/virtualenvs/lzrdbot-QMN38oMy-py3.8/lib/python3.8/site-packages/dataclass_factory/parsers.py", line 80, in <genexpr>
    dyn_element_parser(item_parser, x, i) for i, x in enumerate(data)
  File "/home/lzrdblzzrd/.cache/pypoetry/virtualenvs/lzrdbot-QMN38oMy-py3.8/lib/python3.8/site-packages/dataclass_factory/parsers.py", line 51, in dyn_element_parser
    raise InvalidFieldError(str(e), [str(key)])
dataclass_factory.exceptions.InvalidFieldError: Invalid data at path [1, _sections, track]: No suitable parsers in union found for `{'type': 'LYRICS', 'text': ['Haha!', "It's Reid", 'Welcome to my hotel room', 'A hotel room freestyle', "You already know, let's go", 'It goes like this, it goes exactly like this', '', 'Life goes on like a windmill', 'Only plot I got is to grip steal, make a mill', "Stayin' real, always ill from 1993 til", 'Souls of mischief did it better still', 'Whatever on ya skin like leather', 'Flap ya like a feather', "Don't depend on the weather", "You know I'm better", 'Than most these clowns', "Ya be seein' on the TV", "Cause I don't need cream, I got enough for me see", "I'm like a dairy farm I make cheese when I please", 'This untapped potential have you stuck on ya knees', 'Spewing goop like a slut when they sneeze', 'Jack ya wallet with ease', 'Bruised lids from a lack of sleep', 'Put a chrome to ya dome and eject the meat', "I'll take my seat now", 'Big G on the beats, kaplow', "Don't move dude", 'I got some more food for ya mouth', "Turn this old church to a fuckin' slaughterhouse", '', 'But hold the phone', 'Pick up all the pieces of ya head blown', "I love drugs but I'll never condone", 'Knockout a cop in the comfort of my own home', "Fuck pigs til I'm six feet overgrown", 'Head to hell screamin\' "Fuck 12"', "'Til I'm out the ozone", "Then dust 'em off like a camera lens", 'Whip a Benz', "Y'all should really see how far my shawty bends", 'And how my shotty ends life', 'Put 2 through you and save the rest for ya wife, bitch good night', 'I love my wife, but fuck life', 'Could get a murder charge just to see what the fuck it feels like', 'Leave me alone', 'Could give a fuck who you with bitch', 'I said leave me alone', 'Feed ya Momma a bone', 'Give her a treat if she make me a scone', 'Live ya life and get the fuck off ya phone', "Appreciate the moment and you'll never be alone", '', "I can't surf, but I'm gnar like Spicolli", 'Flat ya like some dough', 'And cut ya up like pepperoni', 'Personal pan pizza in the oven', "Bitch I'm hungry", 'I eat these fools faster than a motherfucking humvee', 'My honey got a rump that make', 'Humpty Dumpty land on his feet', 'Capiche?', 'Damn Reid be off the leash', '', 'I been kicked around, eaten up chewed and spit out', 'My mind was torn into pieces so I ripped that shit out', "Ten years down the drain, guess I wasn't cut out", 'Fast forward 2020, who you listen to now? (Reid)', "Mothafucka's gettin' sick off the clout", "They'd rather suck each other off", 'Instead of figure it out', "Reid's here to patch it up like a squeaky leaky water spout (Bitch)", '', 'Like a squeaky leaky water spout (Uh, Bitch)', 'Imma clean this shit up', 'Imma kill this shit', 'Just for fun', "I don't even have to", "Someone's gotta do it", "That's why I'm here", 'Hot Vodka Volume 1'], 'footer': 'Writer(s): Tanner Petulla\nLyrics powered by www.musixmatch.com', 'tabname': 'Lyrics', 'beacondata': {'lyricsid': '27638669', 'providername': 'musixmatch', 'commontrackid': '110409337'}}`
Suberrors:
  * get_complex_parser.<locals>.complex_parser: __init__() missing 2 required positional arguments: 'meta_pages' and 'metadata'
  * get_complex_parser.<locals>.complex_parser: __init__() missing 1 required positional argument: 'youtube_url'
  * get_complex_parser.<locals>.complex_parser: __init__() missing 1 required positional argument: 'url'


```

**Comment by lzrdblzzrd** [comment]
It is worth adding that this track is an exception to a large number of tracks that have been shazamed normally. On many other tracks everything works fine, but there are exceptions, such as for example this track, on which, for some reason, a parsing error comes out.

**Comment by dotX12** [comment]
Fixes on: https://github.com/dotX12/ShazamIO/releases/tag/0.1.1.0
