### ISSUE TITLE
I am Having Issue on Song Recognize

### ISSUE THREAD

**Issue by Farhanaziz95** [dotX12/ShazamIO#46]
This is the function im trying to use
          async def main():
                shazam = Shazam()
                out = await shazam.recognize_song(f'./Audio_Clean/'+str(Video_ID)+'_'+str(Account_ID)+'_'+str(splite_id)+'.mp3')
                print(out)

                serialized = Serialize.full_track(out)
                print(serialized)

            loop = asyncio.get_event_loop_policy().get_event_loop()
            loop.run_until_complete(main())

and i'm getting an error like this

C:\Users\farha\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "C:\Users\farha\Desktop\Youtube Project\Automation Script Project\download.py", line 4, in <module>
    Download_Tiktok_Videos("tiktokvideos")
  File "C:\Users\farha\Desktop\Youtube Project\Automation Script Project\Tiktok_Scrap.py", line 625, in Download_Tiktok_Videos
    loop.run_until_complete(fatch_audio_Description())
  File "C:\Users\farha\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\farha\Desktop\Youtube Project\Automation Script Project\Tiktok_Scrap.py", line 621, in fatch_audio_Description
    fileoutput = await shazam.recognize_song('./Audio_Clean/'+str(Video_ID)+'_'+str(Account_ID)+'_'+str(splite_id)+'.mp3')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\farha\AppData\Local\Programs\Python\Python311\Lib\site-packages\shazamio\api.py", line 324, in recognize_song
    song = await get_song(data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\farha\AppData\Local\Programs\Python\Python311\Lib\site-packages\shazamio\utils.py", line 39, in get_song
    return AudioSegment.from_file(BytesIO(song_bytes))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\farha\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\farha\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\farha\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\farha\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1491, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

and i'm finding it hard to fix don't know whats wrong i double check the files existense but still the same issue

**Comment by dotX12** [comment]
@Farhanaziz95, hello!
need install ffmpeg.

**Comment by Farhanaziz95** [comment]
Yup thought so did install it at night but forgot to update you that solved the problem
